Repository spidernet-io/cni-plugins, pull requests merged in 2022-11, with the labels that each got.

#88 opt validate overlaySubnet and overlaySubnet, and add unit tests
  pkg/config/config.go
  pkg/config/config_test.go
  plugins/router/router.go
  plugins/veth/veth.go
Labels: kind/feature, kind/cleanup

#86 add macvlan overlay e2e
  plugins/router/README.md
  test/Makefile
  test/Makefile.defs
  test/e2e/common/common.go
  test/e2e/common/const.go
  test/e2e/common/kind.go
  test/e2e/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/macvlan-standalone-one/macvlan_standalone_one_suite_test.go
  test/scripts/install/02-multus-underlay.sh
  test/scripts/install/03-spiderpool.sh
Labels: kind/feature

#91 support ipv4-only and ipv6-only
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e-init.yaml
  .github/workflows/e2e-test.yaml
Labels: kind/feature, kind/cleanup

#93 fix wrong cni-package url when 'RUN_ON_LOCAL'=false
  .github/workflows/ci-bot.yaml
  .github/workflows/e2e-init.yaml
  test/Makefile
  test/scripts/install/01-default-cni.sh
  test/scripts/install/04-cni-plugins.sh
  test/scripts/network-config.sh
Labels: kind/bug

#92 unit test
  .github/workflows/e2e-init.yaml
  .github/workflows/image-build.yaml
  .github/workflows/lint-golang.yaml
  Makefile
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  plugins/router/router.go
  plugins/router/router_suite_test.go
  plugins/router/router_test.go
  test/Makefile
  test/config/calico.yaml
  test/e2e/common/common.go
  test/e2e/common/kind.go
  test/e2e/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/macvlan-standalone-one/macvlan_standalone_one_suite_test.go
  test/e2e/macvlan-standalone-one/macvlan_standalone_one_test.go
  test/scripts/install/01-default-cni.sh
  test/scripts/install/02-multus-underlay.sh
  test/scripts/network-config.sh
  test/scripts/update_repo.sh
  vendor/github.com/containernetworking/plugins/pkg/testutils/bad_reader.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/cmd.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/dns.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/netns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/ping.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/testing.go
  vendor/modules.txt
Labels: kind/feature

#96 create an issue when night ci failed
  .github/workflows/ci-bot.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/e2e-test.yaml
  .github/workflows/image-build.yaml
  .github/workflows/lint-golang.yaml
Labels: kind/bug, kind/feature

#97 unit-test1
  .github/workflows/e2e-test.yaml
  .github/workflows/lint-golang.yaml
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
Labels: kind/feature

#98 typo
  .github/workflows/e2e-init.yaml
  test/Makefile
  test/scripts/install/02-multus-underlay.sh
Labels: kind/bug

#99 fix failed to get defaultOverlayIP
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/image-build.yaml
  pkg/utils/utils_test.go
  plugins/router/router.go
Labels: kind/bug

#100 create an issue
  .github/workflows/e2e-init.yaml
  .github/workflows/e2e-test.yaml
Labels: kind/bug

#102 add spiderdoctor overlay e2e
  test/e2e/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/macvlan-overlay-two/macvlan_overlay_two_suite_test.go
  test/e2e/macvlan-overlay-two/macvlan_overlay_two_test.go
  test/e2e/macvlan-standalone-one/macvlan_standalone_one_test.go
  test/e2e/macvlan-standalone-two/macvlan_standalone_two_suite_test.go
  test/e2e/macvlan-standalone-two/macvlan_standalone_two_test.go
Labels: kind/cleanup

#103 Update changelog and ready to release v0.1.9
  .github/workflows/release.yaml
  charts/meta-plugins/Chart.yaml
  charts/meta-plugins/values.yaml
  docs/Release.md
Labels: kind/feature

#104 add design.md doc
  .github/workflows/image-build.yaml
  docs/Design.md
Labels: kind/doc

#105 fix auto release by workflow_dispatch
  .github/workflows/image-build.yaml
  .github/workflows/release.yaml
Labels: kind/cleanup

#112 update changelog
  .github/workflows/release.yaml
Labels: kind/bug

#111 fix pod failed to visit host when host multi-nic
  pkg/utils/utils.go
  plugins/router/router.go
Labels: kind/bug

#113 robot Update changelog-${latest_release}.md to branch gh-pages
  changelog-v0.2.0.md
Labels: kind/bug

#115 y branch
  .github/workflows/e2e-test.yaml
  .github/workflows/image-build.yaml
  .github/workflows/release.yaml
  docs/Release.md
  images/Dockerfile
Labels: kind/cleanup

#116 fix dockerfile wrong arch
  images/Dockerfile
Labels: kind/cleanup
